FROM nginx:latest

#RUN apt-get update
#RUN apt-get install -y vim
#RUN apt-get install -y cron
#RUN apt-get install -y certbot


# RUN certbot certonly --webroot
# RUN certbot renew --dry-run

# docker run -it --rm --name certbot \
#   -v '/etc/letsencrypt:/etc/letsencrypt' \
#   -v '/var/lib/letsencrypt:/var/lib/letsencrypt' \
#   certbot/certbot certonly -d 'm.lifeguard100.com' --manual --preferred-challenges dns --server https://acme-v02.api.letsencrypt.org/directory