-- CREATE TABLE LARAVELDB.posts(
--     id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
--     title VARCHAR(255),
--     body TEXT
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- INSERT INTO LARAVELDB.posts(title, body) VALUES('My Title', 'My Body');

-- CREATE USER 'test' IDENTIFIED BY 'secret';
-- GRANT ALTER, CREATE, INSERT, SELECT, DELETE, REFERENCES, UPDATE, DROP, EXECUTE, LOCK TABLES, INDEX ON LARAVELDB.* TO 'laravel';
-- GRANT ALTER, CREATE, INSERT, SELECT, DELETE, REFERENCES, UPDATE, DROP, EXECUTE, LOCK TABLES, INDEX ON LARAVELDB.* TO 'laravel'@'%' IDENTIFIED BY 'secret';
-- FLUSH PRIVILEGES;